apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: rh-trex-dummy-3
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rh-trex-dummy-3
    app.kubernetes.io/part-of: nudge-test
  name: rh-trex-dummy-3
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: rh-trex-dummy-3
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: rh-trex-dummy-3
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rh-trex-tenant/nudge-test/rh-trex-dummy-3@sha256:5a094ea084b3176407b7fc9a4d7c419cc2d7c891b82a80fb7e833d2978c921fc
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources: {}
status: {}
