apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: rh-trex-dummy-3
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rh-trex-dummy-3
    app.kubernetes.io/part-of: nudge-test
  name: rh-trex-dummy-3
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: rh-trex-dummy-3
status:
  loadBalancer: {}
