apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: rh-trex-dummy-2
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rh-trex-tenant/nudge-test/rh-trex-dummy-2@sha256:e71ed010abc194fca9a634054343d393297bdbb48b93f7c744fa5c3a157d8126
        name: container-image
        resources: {}
status: {}
