apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: rh-trex-dummy-1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rh-trex-dummy-1
    app.kubernetes.io/part-of: nudge-test
  name: rh-trex-dummy-1
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: rh-trex-dummy-1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: rh-trex-dummy-1
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rh-trex-tenant/nudge-test/rh-trex-dummy-1@sha256:13d2a5cfa7c35199b3705730895c8991790ca650f39540b69509cc1e4947c790
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
