apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: rh-trex-dummy-2
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rh-trex-dummy-2
    app.kubernetes.io/part-of: nudge-test
  name: rh-trex-dummy-2
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: rh-trex-dummy-2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: rh-trex-dummy-2
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rh-trex-tenant/nudge-test/rh-trex-dummy-2@sha256:12982850a2cad4afe6645fa197e1be928284c074dffdc49003cf6ae63294af4a
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
