apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: rh-trex-dummy-1
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rh-trex-tenant/nudge-test/rh-trex-dummy-1@sha256:13d2a5cfa7c35199b3705730895c8991790ca650f39540b69509cc1e4947c790
        name: container-image
        resources: {}
status: {}
